apiVersion: v1
kind: Service
metadata:
  name: test10
  namespace: mynamespace
  labels:
    app: test10
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: test10
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test10
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: test10
  serviceName: "test10"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: test10
    spec:
      containers:
      - name: test10
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
