# kubectl -n mynamespace create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123
apiVersion: v1
stringData:
  DB_Host: sql01
  DB_User: root
  DB_Password: password123
kind: Secret
metadata:
  name: db-secret
  namespace: mynamespace
type: generic
