apiVersion: v1
kind: Service
metadata:
  name: service-test1
  namespace: mynamespace
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: 
    run: service-test1